name: pedidocompra
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  d_chart: ^2.6.7
  fl_chart: ^0.69.0
  table_calendar: ^3.0.8
  #date_time_picker: ^2.1.0
  datetime_picker_formfield_new: ^2.1.0
  date_field: ^6.0.3+1
  font_awesome_flutter: ^10.8.0
  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^11.0.0
  url_launcher: ^6.3.1

  
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo_Biosat.png
    - assets/images/fundoTelaPrincipalBiosat.png
    - assets/images/fundoTelaPrincipalBiosat3.png
    - assets/images/logo_biosat2.png
    - assets/images/Logo_Brumed.png
    - assets/images/logo_big.png
    - assets/images/logo_libertad.png
    - assets/images/logo_emed.png
    - assets/images/agenda.png
    - assets/images/customers.png
    - assets/images/formularios.png
    - assets/images/teamwork.png
    - assets/images/money.png
    - assets/images/grupo_abduch.png
    - assets/images/FUNDO_BIOSAT_APP_640.jpg
    - assets/images/icone_Compras.png
    - assets/images/icone_Compras_02.png
    - assets/images/icone_Compras_03.png
    - assets/images/icone_Crm.png
    - assets/images/icone_Crm_02.png
    - assets/images/icone_Crm_03.png
    - assets/images/Modulo_Compras_Liberttad.png
    - assets/images/Modulo_Compras_Liberttad_02.png
    - assets/images/Modulo_Compras_Liberttad_03.png
    - assets/images/Modulo_Compras_Biosat_Fabrica.png
    - assets/images/Modulo_Compras_Biosat_Fabrica_02.png
    - assets/images/Modulo_Compras_Biosat_Fabrica_03.png
    - assets/images/Modulo_Compras_Biosat_Adm.png
    - assets/images/Modulo_Compras_Biosat_Adm_02.png
    - assets/images/Modulo_Compras_Biosat_Adm_03.png
    - assets/images/Modulo_Compras_Big_Assistencia.png
    - assets/images/Modulo_Compras_Big_Assistencia_02.png
    - assets/images/Modulo_Compras_Big_Assistencia_03.png
    - assets/images/Modulo_Compras_Big_Locacao.png
    - assets/images/Modulo_Compras_Big_Locacao_02.png
    - assets/images/Modulo_Compras_Big_Locacao_03.png
    - assets/images/Modulo_Compras_Emed.png
    - assets/images/Modulo_Compras_Emed_02.png
    - assets/images/Modulo_Compras_Emed_03.png
    - assets/images/Modulo_Compras_Brumed.png
    - assets/images/Modulo_Compras_Brumed_02.png
    - assets/images/Modulo_Compras_Brumed_03.png
    - assets/images/iconesCrm/Agenda.png
    - assets/images/iconesCrm/Agenda_2.png
    - assets/images/iconesCrm/Agenda_3.png
    - assets/images/iconesCrm/Clientes.png
    - assets/images/iconesCrm/Clientes_2.png
    - assets/images/iconesCrm/Clientes_3.png
    - assets/images/iconesCrm/Concorrentes.png
    - assets/images/iconesCrm/Concorrentes_2.png
    - assets/images/iconesCrm/Concorrentes_3.png
    - assets/images/iconesCrm/Medicos.png
    - assets/images/iconesCrm/Medicos_2.png
    - assets/images/iconesCrm/Medicos_3.png
    - assets/images/iconesCrm/Contatos.png 
    - assets/images/iconesCrm/Contatos_2.png 
    - assets/images/iconesCrm/Contatos_3.png
    - assets/images/iconesCrm/Visitas.png
    - assets/images/iconesCrm/Visitas_2.png 
    - assets/images/iconesCrm/Visitas_3.png  
    - assets/images/iconesCrm/Prospects.png 
    - assets/images/iconesCrm/Prospects_2.png 
    - assets/images/iconesCrm/Prospects_3.png 
    - assets/images/iconesCrm/Agenda_tipo2.png 
    - assets/images/iconesCrm/Agenda_02_tipo2.png 
    - assets/images/iconesCrm/Agenda_03_tipo2.png 
    - assets/images/iconesCrm/Concorrentes_tipo2.png
    - assets/images/iconesCrm/Concorrentes_02_tipo2.png 
    - assets/images/iconesCrm/Concorrentes_03_tipo2.png 
    - assets/images/iconesCrm/Contatos_tipo2.png
    - assets/images/iconesCrm/Contatos_02_tipo2.png 
    - assets/images/iconesCrm/Contatos_03_tipo2.png 
    - assets/images/iconesCrm/Medicos_tipo2.png
    - assets/images/iconesCrm/Medicos_02_tipo2.png 
    - assets/images/iconesCrm/Medicos_03_tipo2.png 
    - assets/images/iconesCrm/Prospects_tipo2.png
    - assets/images/iconesCrm/Prospects_02_tipo2.png 
    - assets/images/iconesCrm/Prospects_03_tipo2.png  
    - assets/images/iconesCrm/Visitas_tipo2.png
    - assets/images/iconesCrm/Visitas_02_tipo2.png 
    - assets/images/iconesCrm/Visitas_03_tipo2.png        
    - assets/images/fundos/FUNDO_BIOSAT_APP_02_640.jpg   
    - assets/images/fundos/FUNDO_BIOSAT_APP_02_920.jpg     
    - assets/images/fundos/FUNDO_BIOSAT_APP_02_1080.jpg    
    - assets/images/fundos/FUNDO_BIOSAT_APP_640.jpg 
    - assets/images/fundos/FUNDO_BIOSAT_APP_920.jpg    
    - assets/images/fundos/FUNDO_BIOSAT_APP_1080.jpg     
    - assets/images/logos/Icone_Biosat_Branco.png  
    - assets/images/logos/Icone_Biosat_Branco_02.png   
    - assets/images/logos/Icone_Biosat_Branco_03.png
    - assets/images/logos/Icone_Biosat.png   
    - assets/images/logos/Icone_Biosat_02.png   
    - assets/images/logos/Icone_Biosat_03.png 
    - assets/images/logos/Icone_Brumed.png
    - assets/images/logos/Icone_Brumed_02.png
    - assets/images/logos/Icone_Brumed_03.png
    - assets/images/logos/Icone_EMed.png
    - assets/images/logos/Icone_EMed_02.png  
    - assets/images/logos/Icone_EMed_03.png
    - assets/images/logos/Icone_Liberttad.png
    - assets/images/logos/Icone_Liberttad_02.png 
    - assets/images/logos/Icone_Liberttad_03.png          
    - assets/images/logos/Icone_Big.png 
    - assets/images/logos/Icone_Big_02.png   
    - assets/images/logos/Icone_Big_03.png     
    - assets/images/logos/Logo_Abduch.png
    - assets/images/logos/Logo_Abduch_02.png   
    - assets/images/logos/Logo_Abduch_03.png
    - assets/images/logos/Logo_Biosat_PaginaInicial.png 
    - assets/images/logos/Logo_Biosat_PaginaInicial_02.png 
    - assets/images/logos/Logo_Biosat_PaginaInicial_03.png   
    - assets/images/botoes/aprovar.png  
    - assets/images/botoes/aprovar_02.png  
    - assets/images/botoes/reprovar.png   
    - assets/images/botoes/reprovar_2.png   
    - assets/images/botoes/visualizar.png   
    - assets/images/botoes/visualizar_02.png      
    - assets/images/botoes/visualizar_tipo2.png   
    - assets/images/botoes/visualizar_tipo2_02.png 
    - assets/images/botoes/aprovar_tipo2_02.png
    - assets/images/botoes/aprovar_tipo2.png 
    - assets/images/botoes/reprovar_tipo2.png 
    - assets/images/botoes/reprovar_02_tipo2.png 
    - assets/images/botoes/botao_Aprovacao.png     
    - assets/images/botoes/botao_Aprovacao_02.png   
    - assets/images/botoes/botao_Aprovacao_03.png   
    - assets/images/botoes/botao_Entrega.png
    - assets/images/botoes/botao_Entrega_02.png    
    - assets/images/botoes/botao_Entrega_03.png    
    - assets/images/menuEmpresas/Modulo_Compras_Big_Assistencia_tipo2.png 
    - assets/images/menuEmpresas/Modulo_Compras_Big_Assistencia_02_tipo2.png   
    - assets/images/menuEmpresas/Modulo_Compras_Big_Assistencia_03_tipo2.png  
    - assets/images/menuEmpresas/Modulo_Compras_Big_Locacao_tipo2.png 
    - assets/images/menuEmpresas/Modulo_Compras_Big_Locacao_02_tipo2.png   
    - assets/images/menuEmpresas/Modulo_Compras_Big_Locacao_03_tipo2.png  
    - assets/images/menuEmpresas/Modulo_Compras_Biosat_Adm_tipo2.png   
    - assets/images/menuEmpresas/Modulo_Compras_Biosat_Adm_02_tipo2.png
    - assets/images/menuEmpresas/Modulo_Compras_Biosat_Adm_03_tipo2.png 
    - assets/images/menuEmpresas/Modulo_Compras_Biosat_Fabrica_tipo2.png
    - assets/images/menuEmpresas/Modulo_Compras_Biosat_Fabrica_02_tipo2.png  
    - assets/images/menuEmpresas/Modulo_Compras_Biosat_Fabrica_03_tipo2.png 
    - assets/images/menuEmpresas/Modulo_Compras_Brumed_tipo2.png
    - assets/images/menuEmpresas/Modulo_Compras_Brumed_02_tipo2.png     
    - assets/images/menuEmpresas/Modulo_Compras_Brumed_03_tipo2.png   
    - assets/images/menuEmpresas/Modulo_Compras_Emed_tipo2.png
    - assets/images/menuEmpresas/Modulo_Compras_Emed_02_tipo2.png     
    - assets/images/menuEmpresas/Modulo_Compras_Emed_03_tipo2.png  
    - assets/images/menuEmpresas/Modulo_Compras_Liberttad_tipo2.png
    - assets/images/menuEmpresas/Modulo_Compras_Liberttad_02_tipo2.png  
    - assets/images/menuEmpresas/Modulo_Compras_Liberttad_03_tipo2.png                                                 
    - assets/fonts/Arial_Regular.ttf




    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
